MiAgenda/config/routes.rb
Rails.application.routes.draw do

  
 
  

  
  resources :asignatures, except: [:delete]

  resources :duties, except: [:show]
 

  
  devise_for :users 

  root 'welcome#Index'

end

MiAgenda/app/models/asignature.rb
class Asignature < ActiveRecord::Base
end

MiAgenda/app/models/duty.rb
class Duty < ActiveRecord::Base
  belongs_to :user
  belongs_to :asignature
end

MiAgenda/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :duties       
end

MiAgenda/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

MiAgenda/app/controllers/asignatures_controller.rb
class AsignaturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_asignature, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @asignatures = Asignature.all
    respond_with(@asignatures)
  end

  def show
    respond_with(@asignature)
  end

  def new
    @asignature = Asignature.new
    respond_with(@asignature)
  end

  def edit
  end

  def create
    @asignature = Asignature.new(asignature_params)
    @asignature.save
    respond_with(@asignature)
  end

  def update
    @asignature.update(asignature_params)
    respond_with(@asignature)
  end

  def destroy
    @asignature.destroy
    respond_with(@asignature)
  end

  private
    def set_asignature
      @asignature = Asignature.find(params[:id])
    end

    def asignature_params
      params.require(:asignature).permit(:tittle, :semester)
    end
end

MiAgenda/app/controllers/duties_controller.rb
class DutiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_duty, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @duties = Duty.all
    @asignatures = Asignature.all
    respond_with(@duties)
  end

  def show
    respond_with(@duty)
  end

  def new
    @duty = Duty.new
    respond_with(@duty)
  end

  def edit
  end

  def create
    @duty = current_user.duties.new(duty_params)
    @duty.save
    redirect_to duties_path
    
  
  end

  def update
    @duty.update(duty_params)
    redirect_to duties_path
  end

  def destroy
    @duty.destroy
    respond_with(@duty)
  end

  private
    def set_duty
      @duty = Duty.find(params[:id])
    end

    def duty_params
      params.require(:duty).permit(:tittle, :body, :date_of_delivery,:priority, )
    end
end

MiAgenda/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def Index
    @duties = Duty.all
  end
end

MiAgenda/app/helpers/application_helper.rb
module ApplicationHelper
end

MiAgenda/app/helpers/asignatures_helper.rb
module AsignaturesHelper
end

MiAgenda/app/helpers/duties_helper.rb
module DutiesHelper
end

MiAgenda/app/helpers/migrations_helper.rb
module MigrationsHelper
end

MiAgenda/app/helpers/welcome_helper.rb
module WelcomeHelper
end

MiAgenda/app/views/asignatures/_form.html.erb
<%= form_for(@asignature) do |f| %>
  <% if @asignature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asignature.errors.count, "error") %> prohibited this asignature from being saved:</h2>

      <ul>
      <% @asignature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tittle %><br>
    <%= f.text_field :tittle %>
  </div>
  <div class="field">
    <%= f.label :semester %><br>
    <%= f.text_field :semester %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MiAgenda/app/views/asignatures/edit.html.erb
<h1>Editing asignature</h1>

<%= render 'form' %>

<%= link_to 'Show', @asignature %> |
<%= link_to 'Back', asignatures_path %>

MiAgenda/app/views/asignatures/index.html.erb
<h1>Listing asignatures</h1>

<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Semester</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asignatures.each do |asignature| %>
      <tr>
        <td><%= asignature.tittle %></td>
        <td><%= asignature.semester %></td>
        <td><%= link_to 'Show', asignature %></td>
        <td><%= link_to 'Edit', edit_asignature_path(asignature) %></td>
        <td><%= link_to 'Destroy', asignature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asignature', new_asignature_path %>

MiAgenda/app/views/asignatures/new.html.erb
<h1>New asignature</h1>

<%= render 'form' %>

<%= link_to 'Back', asignatures_path %>

MiAgenda/app/views/asignatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tittle:</strong>
  <%= @asignature.tittle %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @asignature.semester %>
</p>

<%= link_to 'Edit', edit_asignature_path(@asignature) %> |
<%= link_to 'Back', asignatures_path %>

MiAgenda/app/views/duties/_form.html.erb
<%= form_for(@duty)  do |f|  %>
    <div class="container ">
    <% if @duty.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@duty.errors.count, "error") %> prohibited this duty from being saved:</h2>
        <ul>
        <% @duty.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="input-field col s6">
      <%= f.label :tittle %><br>
      <%= f.text_field :tittle %>
    </div>
    <div class="input-field col s6">
      <%= f.label :body %><br>
      <%= f.text_area :body, class:"materialize-textarea" %>
    </div>
    
    <div class="input-field col s6">
      <%= f.label :priority %><br>
      <p class="range-field">
      <%= f.range_field :priority, :min=>0, :max=>100, :class=>"slide", :id=>"slider1"%>
    </div>

    <div class="input-field col s6">
      <%= f.label :date_of_delivery %><br>
      <%= f.date_field :date_of_delivery, class:"datepicker" %>
    </div>

    <div class="actions">
      <%= f.submit "Enviar", class:"waves-effect waves-light btn-large center-align"%>
    </div>
    </div>
  <% end %>

MiAgenda/app/views/duties/_index.html.erb
<h1>Tareas pendientes</h1>
<div class="row section scrollspy">
      <!-- Page Content goes here -->
      <% @duties.each do |duty| %>
        <%if current_user.id == duty.user_id &&  duty.date_of_delivery > Time.now %>
          <div class="row">
          <div class="col s4 m0">
          <div class="card">
           <% puts case duty.priority %>
           <% when 0..20 %>
            <div class="card brown darken-2">
           <% when 21..40 %>
           <div class="card purple darken-2">
           <% when 41..60 %>
           <div class="card green darken-2">
           <% when 61..80 %>
           <div class="card blue darken-2">
           <% when 81..100 %>
           <div class="card red darken-2">
           <%end%>
            
            <div class="card-content white-text">
              <span class="card-title"><%= duty.tittle %></span>
              <p><%= duty.body %>.</p>
              <i class="small material-icons middle-xs">today</i><%= duty.date_of_delivery %>
            </div>
            <div class="card-action">
              <a><%= link_to 'Edit', edit_duty_path(duty) %></a>
              <a><%= link_to 'Destroy', duty, method: :delete, data: { confirm: 'Are you sure?' } %></a>
            </div>
          </div>
          </div>
         </div>
        <%end%>
      <%end%>

  </div>

MiAgenda/app/views/duties/edit.html.erb
<h1>Editing duty</h1>

<%= render 'form' %>

<%= link_to 'Show', @duty %> |
<%= link_to 'Back', duties_path %>

MiAgenda/app/views/duties/index.html.erb
<%=render "duties/index"%>

MiAgenda/app/views/duties/new.html.erb
<h2 class="center">Nueva tarea</h2>

<%= render 'form' %>

<%= link_to 'Back', duties_path %>

MiAgenda/app/views/duties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @duty.user %>
</p>

<p>
  <strong>Tittle:</strong>
  <%= @duty.tittle %>
</p>

<p>
  <strong>Body:</strong>
  <%= @duty.body %>
</p>

<p>
  <strong>Date of delivery:</strong>
  <%= @duty.date_of_delivery %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @duty.priority %>
</p>

<%= link_to 'Edit', edit_duty_path(@duty) %> |
<%= link_to 'Back', duties_path %>

MiAgenda/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiAgenda</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/navigation' %>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


<%= yield %>


</body>
</html>

MiAgenda/app/views/partials/_navigation.html.erb
<header>
    
    <nav>
    <% if user_signed_in? %>
         <ul id="slide-out" class="side-nav">
          
          <li><a><h4>Mis Materias</h4></a></li>
          <a href="#!" class="teal darken-2" style="color: white; text-align: center;">PROLOG</a>
        </ul>
        <a href="#" data-activates="slide-out" class="button-collapse show-on-large"><i class="mdi-navigation-menu"></i></a>
        
    <%end%>
    <div class="nav-wrapper  blue-grey darken-2">
      <a class="brand-logo center"><%= link_to "Mi Agenda", root_path, class:"center"%></a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li class="col-md">
            <% if user_signed_in? %>
                <%= current_user.email %>
            <%end%>
        </li>
        <% if user_signed_in? %>
            <li class="col-md">
                <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>    
            </li>
            <div class="container">
                <div class="row">
                    <div class="fixed-action-btn horizontal" style="bottom: 0px; right: 24px;">
                        <a href= "duties/new"class="btn-floating btn-large red">
                        
                        <i class="large material-icons">add </i></a>
                        
                    </div>
                </div>
            </div>
        <%else %>
            <li class="col-md">
                <%= link_to "Iniciar Sesión", new_user_session_path%>
            </li>
            <li class="col-md">
                <%= link_to "Regittrarte", new_user_registration_path%>
            </li>
        <%end %>
      </ul>
    </div>
    
</header>

MiAgenda/app/views/welcome/Index.html.erb
<% if user_signed_in? %>
<%=render "duties/index"%>
<%end%>